apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-user-passwords
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tradebot-vault
    kind: ClusterSecretStore
  target:
    name: kafka-user-passwords
    creationPolicy: Owner
  data:
    - secretKey: data-service
      remoteRef: { key: tradebot-test/kafka/data-service, property: password }
    - secretKey: gateway-service
      remoteRef: { key: tradebot-test/kafka/gateway-service, property: password }
    - secretKey: kraken-ingest
      remoteRef: { key: tradebot-test/kafka/kraken-ingest, property: password }
    - secretKey: yahoo-ingest
      remoteRef: { key: tradebot-test/kafka/yahoo-ingest, property: password }
    - secretKey: oms-service
      remoteRef: { key: tradebot-test/kafka/oms-service, property: password }
    - secretKey: bot-engine
      remoteRef: { key: tradebot-test/kafka/bot-engine, property: password }
    - secretKey: user-service
      remoteRef: { key: tradebot-test/kafka/user-service, property: password }
