migration:
  enabled: true
  repository: registry.margusm.dev/devprojects/tradebot-2/db-migrator-gateway
  tag: 0f277bab
  dbUrl: jdbc:postgresql://cloudy-vm.margusm.dev:5534/tradebot
  eso:
    data:
      - secretKey: LIQUIBASE_DB_USERNAME
        remoteRef: { key: tradebot-test/gateway, property: db-migrator-username }
      - secretKey: LIQUIBASE_DB_PASSWORD
        remoteRef: { key: tradebot-test/gateway, property: db-migrator-password }

image:
  repository: registry.margusm.dev/devprojects/tradebot-2/gateway
  tag: 3a2da2b1

containerPort: 8080
service:
  port: 8080
probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness

env:
  GATEWAY_REDIS_HOST: redis.tradebot-test-base
  GATEWAY_REDIS_PORT: "6379"
  KAFKA_USERNAME: gateway-service
  DATA_SERVICE_URL: http://data-service:8081
  USER_SERVICE_URL: http://user-service:8086
  BOT_ENGINE_URL: http://bot-engine:8087
  ORDER_MANAGEMENT_SERVICE_URL: http://order-management-service:8082

externalDb:
  enabled: true
  stableDns:
    enabled: true
    serviceName: gateway-db
    externalName: cloudy-vm.margusm.dev
  env:
    DB_GATEWAY_URL: r2dbc:postgresql://gateway-db:5534/tradebot?schema=tradebot

secrets:
  eso:
    data:
      - secretKey: DB_GATEWAY_APP_PASSWORD
        remoteRef: { key: tradebot-test/gateway, property: db-password }
      - secretKey: GATEWAY_REDIS_PASSWORD
        remoteRef: { key: tradebot-test/redis, property: password }
      - secretKey: KAFKA_PASSWORD
        remoteRef: { key: tradebot-test/kafka/gateway-service, property: password }
      - secretKey: JWT_SECRET
        remoteRef: { key: tradebot-test/gateway, property: jwt-secret }
