{{- if eq .Values.secrets.mode "eso" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common-service.fullname" . }}-secrets
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.eso.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.eso.secretStoreRef.name }}
    kind: {{ .Values.secrets.eso.secretStoreRef.kind }}
  target:
    name: {{ include "common-service.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- toYaml .Values.secrets.eso.data | nindent 4 }}
{{- end }}
