apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: common-service
    releaseName: order-management-service
    valuesFile: ../common-values.yaml
    additionalValuesFiles:
      - values.yaml
